#!/bin/sh

cmd=`git rev-parse --abbrev-ref HEAD`
branch=${cmd}

if [ $branch == 'master' ]
then
echo '--- Updating docs... ---'
git stash
git checkout gh-pages
git merge master
git push origin gh-pages
git checkout master
git stash apply
echo '--- Updating docs complete! ---'
fi
